import Header from "@/components/Hearder";
// import Header from '../components/Header';
import Header2 from "../components/Header2";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {" "}
        <Header />
        {/* <Header2 /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
